/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.views;

import com.thanhtd.app.App;
import com.thanhtd.controllers.DbController;
import com.thanhtd.controllers.WorkWithExcel;
import com.thanhtd.models.Order;
import com.thanhtd.models.OrderDetail;
import com.thanhtd.models.OrderDetailTableModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Thanh Tran
 */
public class EditOrderFrame extends javax.swing.JFrame {

    Order temp = null;
    List<OrderDetail> data = new LinkedList<>();
    OrderDetailTableModel odtm = new OrderDetailTableModel();

    /**
     * Creates new form EditOrderFrame
     */
    public EditOrderFrame(Order i) {
        initComponents();

        //Set the windows to center of screen
        setLocationRelativeTo(null);

        temp = i;
        editOrderId.setText("" + temp.getID());
        editOrderCusNameTxt.setText(temp.getCusName());
        editOrderCusAddTxt.setText(temp.getCusAdd());
        editOrderCusTelTxt.setText(temp.getCusTel());
        editOrderCusEmailTxt.setText(temp.getCusEmail());

        DbController.ReadOrderDetailFromDB(data, temp.getID());

        App.dataOrderDetail = data;
        odtm.setData(data);
        editOrderTable.setModel(odtm);
        setupTable();

        double tempTotal = 0;
        for (OrderDetail x : data) {
            tempTotal += x.getTotal();
        }
        jLabel8.setText("$" + tempTotal);
        setVisible(true);
    }

    private void setupTable() {
        TableColumn totalCol = editOrderTable.getColumnModel().getColumn(3);
        totalCol.setMaxWidth(65);
        totalCol.setPreferredWidth(65);

        TableColumn quantityCol = editOrderTable.getColumnModel().getColumn(2);
        quantityCol.setMaxWidth(65);
        quantityCol.setPreferredWidth(65);

        TableColumn priceCol = editOrderTable.getColumnModel().getColumn(1);
        priceCol.setMaxWidth(90);
        priceCol.setPreferredWidth(90);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editOrderTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editOrderCusNameTxt = new javax.swing.JTextField();
        editOrderCusAddTxt = new javax.swing.JTextField();
        editOrderCusTelTxt = new javax.swing.JTextField();
        editOrderCusEmailTxt = new javax.swing.JTextField();
        editOrderId = new javax.swing.JLabel();
        editOrderCancelBtn = new javax.swing.JButton();
        editOrderUpdateBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Edit Order");
        setResizable(false);

        jLabel1.setText("Order ID");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Customer Address");

        jLabel4.setText("Customer Telephone");

        jLabel5.setText("Customer Email");

        jLabel6.setText("Order Detail");

        editOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(editOrderTable);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("TotalLabel");

        editOrderCusNameTxt.setText("jTextField1");

        editOrderCusAddTxt.setText("jTextField2");

        editOrderCusTelTxt.setText("jTextField3");

        editOrderCusEmailTxt.setText("jTextField4");

        editOrderId.setText("OrderId");

        editOrderCancelBtn.setText("Close");
        editOrderCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderCancelBtnActionPerformed(evt);
            }
        });

        editOrderUpdateBtn.setText("Save");
        editOrderUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editOrderUpdateBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Export to Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Send Email");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editOrderCusNameTxt)
                            .addComponent(editOrderCusAddTxt)
                            .addComponent(editOrderCusTelTxt)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editOrderId)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editOrderCusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton2)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editOrderUpdateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editOrderCancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editOrderId))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editOrderCusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(editOrderCusAddTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(editOrderCusTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(editOrderCusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editOrderCancelBtn)
                    .addComponent(editOrderUpdateBtn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editOrderCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderCancelBtnActionPerformed
        if (editOrderCusNameTxt.getText().trim().toUpperCase().compareTo(temp.getCusName().toUpperCase()) == 0
                && editOrderCusAddTxt.getText().trim().toUpperCase().compareTo(temp.getCusAdd().toUpperCase()) == 0
                && editOrderCusEmailTxt.getText().trim().toLowerCase().compareTo(temp.getCusEmail()) == 0
                && editOrderCusTelTxt.getText().trim().toUpperCase().compareTo(temp.getCusTel().toUpperCase()) == 0) {
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Customer information changed. Please save before close.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editOrderCancelBtnActionPerformed

    private void editOrderUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editOrderUpdateBtnActionPerformed
        temp.setCusName(editOrderCusNameTxt.getText());
        temp.setCusAdd(editOrderCusAddTxt.getText());
        temp.setCusTel(editOrderCusTelTxt.getText());
        temp.setCusEmail(editOrderCusEmailTxt.getText().toLowerCase());
        DbController.UpdateOrderToDB(temp);
        setVisible(false);
    }//GEN-LAST:event_editOrderUpdateBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WorkWithExcel.ExportToExcel(temp, data);
        JOptionPane.showMessageDialog(this, "File exported!");
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (editOrderCusEmailTxt.getText().trim().toLowerCase().compareTo(temp.getCusEmail()) == 0) {
            EmailConfigFrame emailConfigFrame = new EmailConfigFrame(temp, data);
            emailConfigFrame.getContentPane();
        } else {
            JOptionPane.showMessageDialog(this, "Email changed. Please save before send email.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditOrderFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editOrderCancelBtn;
    private javax.swing.JTextField editOrderCusAddTxt;
    private javax.swing.JTextField editOrderCusEmailTxt;
    private javax.swing.JTextField editOrderCusNameTxt;
    private javax.swing.JTextField editOrderCusTelTxt;
    private javax.swing.JLabel editOrderId;
    private javax.swing.JTable editOrderTable;
    private javax.swing.JButton editOrderUpdateBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
