/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.views;

import com.thanhtd.app.App;
import com.thanhtd.controllers.DbController;
import com.thanhtd.controllers.OrderController;
import com.thanhtd.models.MakeOrder;
import com.thanhtd.models.MakeOrderTableModel;
import com.thanhtd.models.Order;
import com.thanhtd.models.Product;
import com.thanhtd.models.ProductTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author Thanh Tran
 */
public class MakeOrderFrame extends javax.swing.JFrame {

    /**
     * Creates new form MakeOrderFrame
     */
    List<Product> listProducts = new LinkedList<>();
    List<Product> filteredProductList;

    public static List<Product> selectList = new LinkedList<>();
    public static List<Integer> quantityList = new LinkedList<>();

    ProductTableModel ptm = null;
    public static MakeOrderTableModel motm = new MakeOrderTableModel();
    public int orderProduct;
    public int orderNextId;

    public MakeOrderFrame(List<Product> products, List<Order> orders, ProductTableModel table) {
        initComponents();

        //Set the windows to center of screen
        setLocationRelativeTo(null);

        listProducts = products;
        ptm = table;

        orderNextId = App.dataOrder.get(App.dataOrder.size() - 1).getID() + 1;
        makeOrderNextId.setText("" + orderNextId);
        jLabel9.setText("$0.0");

        //Set data to Table
        ptm.setData(listProducts);
        makeOrderProductTable.setModel(table);

        //Set data to Selectd Products Table
        motm.setData(selectList, quantityList);
        makeOrderSelectedProduct.setModel(motm);

        SetupApp();

        setVisible(true);
    }

    private void SetupApp() {
        TableColumn idCol = makeOrderProductTable.getColumnModel().getColumn(0);
        idCol.setMaxWidth(30);
        idCol.setPreferredWidth(30);

        TableColumn pricecol = makeOrderProductTable.getColumnModel().getColumn(2);
        pricecol.setMaxWidth(100);
        pricecol.setPreferredWidth(100);

        TableColumn totalCol2 = makeOrderSelectedProduct.getColumnModel().getColumn(3);
        totalCol2.setMaxWidth(60);
        totalCol2.setPreferredWidth(60);

        TableColumn quantityCol2 = makeOrderSelectedProduct.getColumnModel().getColumn(2);
        quantityCol2.setMaxWidth(60);
        quantityCol2.setPreferredWidth(60);

        TableColumn priceCol2 = makeOrderSelectedProduct.getColumnModel().getColumn(1);
        priceCol2.setMaxWidth(60);
        priceCol2.setPreferredWidth(60);

        makeOrderCusAddTxt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_TAB) {
                    if (e.getModifiers() > 0) {
                        makeOrderCusAddTxt.transferFocusBackward();
                    } else {
                        makeOrderCusAddTxt.transferFocus();
                    }
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        makeOrderCusNameTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        makeOrderCusAddTxt = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        makeOrderCusEmailTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        makeOrderProductTable = new javax.swing.JTable();
        makeOrderCancelBtn = new javax.swing.JButton();
        makeOrderCreateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        makeOrderSearchProductTxt = new javax.swing.JTextField();
        makeOrderNextId = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        makeOrderCusTelTxt = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        makeOrderSelectedProduct = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Make an Order");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Next Order ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Customer Address");

        makeOrderCusAddTxt.setColumns(20);
        makeOrderCusAddTxt.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        makeOrderCusAddTxt.setRows(5);
        makeOrderCusAddTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(makeOrderCusAddTxt);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Customer Telephone");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Customer Email");

        makeOrderProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        makeOrderProductTable.setRowHeight(20);
        makeOrderProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeOrderProductTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(makeOrderProductTable);

        makeOrderCancelBtn.setText("Close");
        makeOrderCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrderCancelBtnActionPerformed(evt);
            }
        });

        makeOrderCreateBtn.setText("Make an Order");
        makeOrderCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeOrderCreateBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Product List");

        makeOrderSearchProductTxt.setText("Search");
        makeOrderSearchProductTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                makeOrderSearchProductTxtFocusLost(evt);
            }
        });
        makeOrderSearchProductTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                makeOrderSearchProductTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                makeOrderSearchProductTxtKeyReleased(evt);
            }
        });

        makeOrderNextId.setText("jLabel8");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("TOTAL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("jLabel9");

        makeOrderSelectedProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        makeOrderSelectedProduct.setRowHeight(20);
        jScrollPane3.setViewportView(makeOrderSelectedProduct);

        jLabel10.setText("Selected Product(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(226, 226, 226)
                        .addComponent(makeOrderSearchProductTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(makeOrderCreateBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(makeOrderCancelBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(makeOrderNextId)
                                        .addGap(266, 266, 266))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(makeOrderCusNameTxt)
                                        .addComponent(jScrollPane1)
                                        .addComponent(makeOrderCusTelTxt)
                                        .addComponent(makeOrderCusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(makeOrderSearchProductTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(makeOrderNextId))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(makeOrderCusNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(makeOrderCusTelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(makeOrderCusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(makeOrderCreateBtn)
                                    .addComponent(makeOrderCancelBtn)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void makeOrderCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrderCancelBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_makeOrderCancelBtnActionPerformed

    private void makeOrderSearchProductTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_makeOrderSearchProductTxtFocusLost
        if (makeOrderSearchProductTxt.getText().compareTo("") == 0) {
            makeOrderSearchProductTxt.setText("Search");
            ptm.setData(listProducts);
            ptm.fireTableDataChanged();
            makeOrderProductTable.setModel(ptm);
        }
    }//GEN-LAST:event_makeOrderSearchProductTxtFocusLost

    private void makeOrderSearchProductTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_makeOrderSearchProductTxtKeyReleased
        if (makeOrderSearchProductTxt.getText().trim().compareTo("") != 0) {
            List<Product> temp = new LinkedList<>();
            for (Product i : listProducts) {
                if (i.getName().toUpperCase().contains(makeOrderSearchProductTxt.getText().toUpperCase())) {
                    temp.add(i);
                }
            }
            filteredProductList = temp;
            ptm.setData(temp);
            ptm.fireTableDataChanged();
            makeOrderProductTable.setModel(ptm);
        } else {
            ptm.setData(listProducts);
            ptm.fireTableDataChanged();
            makeOrderProductTable.setModel(ptm);
        }
    }//GEN-LAST:event_makeOrderSearchProductTxtKeyReleased

    private void makeOrderProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeOrderProductTableMouseClicked
        if (evt.getClickCount() == 2) {
            if (makeOrderSearchProductTxt.getText().trim().compareTo("Search") == 0) {
                orderProduct = makeOrderProductTable.rowAtPoint(evt.getPoint());
                AddProductToOrderFrame addProductToOrderFrame = new AddProductToOrderFrame(listProducts.get(orderProduct));
                addProductToOrderFrame.getContentPane();
            } else {
                ptm.setData(filteredProductList);
                ptm.fireTableDataChanged();
                orderProduct = makeOrderProductTable.rowAtPoint(evt.getPoint());
                AddProductToOrderFrame addProductToOrderFrame = new AddProductToOrderFrame(filteredProductList.get(orderProduct));
                addProductToOrderFrame.getContentPane();
            }
        }
    }//GEN-LAST:event_makeOrderProductTableMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        double total = 0;
        for (int i = 0; i < selectList.size(); i++) {
            total += selectList.get(i).getPrice() * quantityList.get(i);
        }
        jLabel9.setText("$" + total);
    }//GEN-LAST:event_formWindowActivated

    private void makeOrderCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeOrderCreateBtnActionPerformed
        if (makeOrderSelectedProduct.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Please select Product", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (makeOrderCusNameTxt.getText().trim().compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Please fill the Name field.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (makeOrderCusAddTxt.getText().trim().compareTo("") == 0) {
                    JOptionPane.showMessageDialog(this, "Please fill the Address field.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (makeOrderCusTelTxt.getText().trim().compareTo("") == 0) {
                        JOptionPane.showMessageDialog(this, "Please fill the Telephone field.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (makeOrderCusEmailTxt.getText().trim().compareTo("") == 0) {
                            JOptionPane.showMessageDialog(this, "Please fill the Email field.", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            OrderController.AddOrder(App.dataOrder, new Order(orderNextId, makeOrderCusNameTxt.getText(), makeOrderCusAddTxt.getText(), makeOrderCusTelTxt.getText(), makeOrderCusEmailTxt.getText().toLowerCase()));

                            DbController.InsertNewFullOrderToDB(new MakeOrder(orderNextId, makeOrderCusNameTxt.getText(), makeOrderCusAddTxt.getText(), makeOrderCusTelTxt.getText(), makeOrderCusEmailTxt.getText().toLowerCase(), selectList, quantityList));
                            selectList.clear();
                            quantityList.clear();
                            setVisible(false);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_makeOrderCreateBtnActionPerformed

    private void makeOrderSearchProductTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_makeOrderSearchProductTxtKeyPressed
        if (makeOrderSearchProductTxt.getText().compareTo("Search") == 0) {
            makeOrderSearchProductTxt.setText("");
        }
    }//GEN-LAST:event_makeOrderSearchProductTxtKeyPressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MakeOrderFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MakeOrderFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton makeOrderCancelBtn;
    private javax.swing.JButton makeOrderCreateBtn;
    private javax.swing.JTextArea makeOrderCusAddTxt;
    private javax.swing.JTextField makeOrderCusEmailTxt;
    private javax.swing.JTextField makeOrderCusNameTxt;
    private javax.swing.JTextField makeOrderCusTelTxt;
    private javax.swing.JLabel makeOrderNextId;
    private javax.swing.JTable makeOrderProductTable;
    private javax.swing.JTextField makeOrderSearchProductTxt;
    private javax.swing.JTable makeOrderSelectedProduct;
    // End of variables declaration//GEN-END:variables
}
